# Air configuration file for hot reload development
# https://github.com/cosmtrek/air

root = "."
testdata_dir = "tests"
tmp_dir = "bin"

[build]
  args_bin = []
  bin = "./bin/app"
  cmd = "go build -o ./bin/app ."
  delay = 1000
  exclude_dir = ["assets", "tmp"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = true                # Enable polling for Windows/Docker Desktop
  poll_interval = 500        # Check for changes every 500ms
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
