version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fiber_boilerplate_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fiber_boilerplate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fiber_network

  fiber_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiber_boilerplate_app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: fiber_boilerplate
      PORT: 3000
      ENV: production
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fiber_network

volumes:
  postgres_data:

networks:
  fiber_network:
    driver: bridge
